# Generated by Django 6.0.4 on 2026-04-27 08:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(db_column='company_names', max_length=100)),
                ('name', models.CharField(db_column='cars_names', max_length=100)),
                ('engine', models.CharField(blank=True, max_length=100)),
                ('engine_capacity', models.FloatField(blank=True, help_text='CC', null=True)),
                ('horsepower', models.FloatField(blank=True, help_text='HP', null=True)),
                ('total_speed', models.FloatField(blank=True, help_text='km/h', null=True)),
                ('acceleration', models.FloatField(blank=True, help_text='0-100 km/h seconds', null=True)),
                ('price', models.FloatField(blank=True, help_text='Price in $', null=True)),
                ('fuel_type', models.CharField(blank=True, max_length=50)),
                ('seats', models.IntegerField(blank=True, null=True)),
                ('torque', models.FloatField(blank=True, help_text='Nm', null=True)),
            ],
            options={
                'verbose_name_plural': 'cars',
                'db_table': 'api_car',
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('message_type', models.CharField(choices=[('user_input', 'User Input'), ('agent_question', 'Agent Question'), ('comparison', 'Comparison Table'), ('plain_text', 'Plain Text')], max_length=20)),
                ('content', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.chat')),
            ],
        ),
    ]
